# automatically generated by the FlatBuffers compiler, do not modify.

import flatbuffers
from flatbuffers import number_types

class TickDataSequence(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTickDataSequence(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TickDataSequence()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def TickDataSequenceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"", size_prefixed)

    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ticks
    def Ticks(self, j):
        o = self._tab.Offset(4)
        if o != 0:
            vector = self._tab.Vector(o)
            # Accessing the j-th element of the vector (each element is a uoffset to a TickData table)
            start = vector + j * 4
            return self._tab.Indirect(start)
        return 0

    def TicksLength(self):
        o = self._tab.Offset(4)
        if o != 0:
            return self._tab.VectorLen(o)
        return 0


# FlatBuffers builder helpers
def TickDataSequenceStart(builder):
    builder.StartObject(1)

def TickDataSequenceAddTicks(builder, ticks):
    builder.PrependUOffsetTRelativeSlot(0, ticks, 0)

def TickDataSequenceEnd(builder):
    return builder.EndObject()


def TickDataSequenceStartTicksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)
