# automatically generated by the FlatBuffers compiler, do not modify.

import flatbuffers
from flatbuffers import number_types

class TickData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTickData(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TickData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def TickDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"", size_prefixed)

    # TickData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # f0
    def F0(self):
        o = self._tab.Offset(4)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f1
    def F1(self):
        o = self._tab.Offset(6)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f2
    def F2(self):
        o = self._tab.Offset(8)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f3
    def F3(self):
        o = self._tab.Offset(10)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f4
    def F4(self):
        o = self._tab.Offset(12)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f5
    def F5(self):
        o = self._tab.Offset(14)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f6
    def F6(self):
        o = self._tab.Offset(16)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # f7
    def F7(self):
        o = self._tab.Offset(18)
        if o != 0:
            return self._tab.Get(number_types.Float32Flags, o + self._tab.Pos)
        return 0.0


# FlatBuffers builder helpers
def TickDataStart(builder):
    builder.StartObject(8)

def TickDataAddF0(builder, f0):
    builder.PrependFloat32Slot(0, f0, 0.0)

def TickDataAddF1(builder, f1):
    builder.PrependFloat32Slot(1, f1, 0.0)

def TickDataAddF2(builder, f2):
    builder.PrependFloat32Slot(2, f2, 0.0)

def TickDataAddF3(builder, f3):
    builder.PrependFloat32Slot(3, f3, 0.0)

def TickDataAddF4(builder, f4):
    builder.PrependFloat32Slot(4, f4, 0.0)

def TickDataAddF5(builder, f5):
    builder.PrependFloat32Slot(5, f5, 0.0)

def TickDataAddF6(builder, f6):
    builder.PrependFloat32Slot(6, f6, 0.0)

def TickDataAddF7(builder, f7):
    builder.PrependFloat32Slot(7, f7, 0.0)

def TickDataEnd(builder):
    return builder.EndObject()
